### ISSUE TITLE
Error with registry password

### ISSUE THREAD

**Issue by JohannesByle** [Azure/container-apps-deploy-action#102]
After building and pushing the container image my github action (which uses  azure/container-apps-deploy-action@v2) fails with the following error:

```
WARNING: Adding registry password as a secret with name "ghcrio-***"
ERROR: (ContainerAppInvalidPropertyValue) Property 'secrets.name' has an invalid value 'ghcrio-***'. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
```

The azure login, as well as the ghcr push itself succeeds, so I assume my credentials are correct. Is there something I've mis-configured?

**Comment by erikbrgn** [comment]
I'm assuming it's your GH username used for creating the secret. So `ghcrio-***` is actually `ghcrio-JohannesByle` which according to Azure is not a valid format for the name of a secret. The error message points out that `"A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character"`.

I'm encountering a similar issue where the format of my username doesn't satisfy the requirements set in Azure...

**Comment by erikbrgn** [comment]
Yeah, extremely frustrating and I'm guessing it's something that has to be fixed in the Azure CLI rather than in this action
