### ISSUE TITLE
Support additional config

### ISSUE THREAD

**Issue by heddendorp** [Azure/container-apps-deploy-action#12]
I am using yaml to configure size and scaling rules for my conatiner apps right now.
It would be great if this action could also support some advanced config to make the switch easier.

**Comment by cormacpayne** [comment]
@heddendorp Hey Lukas -- apologies for the delayed response; just to make sure I'm on the same page as you, when you say that you're using a YAML file to configure certain configurations of your Container App, is this YAML file being provided to an `az containerapp` command within the Azure CLI, or is there a separate flow you're using this YAML file in? Thanks!

**Comment by cormacpayne** [comment]
@heddendorp Hey Lukas, with the latest `v0` release, you can now use the `yamlConfigPath` argument to provide a YAML configuration file that specifies that properties of the Container App to create or update.

Please feel free to let me know if this doesn't work for, or if there are any additional comments or questions you have. Thanks!
