### ISSUE TITLE
Support GitHub container registry

### ISSUE THREAD

**Issue by heddendorp** [Azure/container-apps-deploy-action#13]
To make my containers generally available I am currently using the github registry, it would be nice if this action could support non azure registries as well.

**Comment by heddendorp** [comment]
@cormacpayne both actually.
I like the "integrated" behavior of building and then deploying an image.
I would be nice to use the GitHub registry instead of the azure one though.

**Comment by cormacpayne** [comment]
@heddendorp Hey Lukas, apologies for the delayed response -- we added support for `registryUrl`, `registryUsername` and `registryPassword` arguments to allow users to provide non-ACR registries as image push/pull sources. When you have the opportunity, would you mind trying it out and letting me know if it's sufficient for your needs with the action? Thanks in advance!

**Comment by cormacpayne** [comment]
@heddendorp I'm going to close this issue as the `registry*` arguments added to this GitHub Action should support the desired use case, but please feel free to let me know otherwise and I'll gladly re-open the issue for further discussion. Thanks!
