### ISSUE TITLE
Regression in https://github.com/Azure/container-apps-deploy-action/pull/35

### ISSUE THREAD

**Issue by jacobATcertifiedfoodDotinfo** [Azure/container-apps-deploy-action#36]
`az containerapp up`
See this line: https://github.com/Azure/container-apps-deploy-action/commit/93b56574635292a3fdfd6c2433e54138057479da#r104806035

```
Run az containerapp up \
ERROR: Failed to retrieve credentials for container registry. Please provide the registry username and password
Error: Process completed with exit code 1.
```

This error started 4 hours ago, which coincides with the merge of https://github.com/Azure/container-apps-deploy-action/pull/35

**Comment by jacobATcertifiedfoodDotinfo** [comment]
I reverted commit 93b5657 in a private git repo clone, and the error is gone.

**Comment by cormacpayne** [comment]
@jacobATcertifiedfoodDotinfo Hey there, apologies that you're running into this issue -- would you mind providing the following information for additional context:

- Which arguments are you providing to the action? (just the argument names, no need for values)
- Are you using this action to create a new Container App or update an existing one?

I'm hoping that if you previously provided the registry credentials, that the underlying API call we're making would respect them when performing the `PATCH` operation with `az containerapp up` and wouldn't require that you provide them again, but it may be the case that they'll need to be provided if you're pulling from a different registry. The information you provide above should shed some more light on this.

**Comment by cormacpayne** [comment]
@jacobATcertifiedfoodDotinfo As a quick update: I pushed a change to the `corm/fix-registry-update` branch that you can test to see if it resolves your issue:

```yaml
- uses: Azure/container-apps-deploy-action@corm/fix-registry-update
```

**Comment by cormacpayne** [comment]
@jacobATcertifiedfoodDotinfo This issue should now be resolved in the latest `v0` release -- please feel free to let us know if you're still seeing this issue.
