### ISSUE TITLE
uses missing colon?

### ISSUE THREAD

**Issue by Danferno** [Azure/container-apps-deploy-action#9]
Github actions was complaining until I replaced all `uses azure/container-apps-deploy-action@v0` by `uses: azure/container-apps-deploy-action@v0` in the examples (added a colon after uses)

**Comment by cormacpayne** [comment]
@Danferno Hey there, thanks for catching this! Looks like we missed the colon for the first example, and it was copy-pasted when creating the subsequent examples 😅 I've opened a [pull request](https://github.com/Azure/container-apps-deploy-action/pull/10) to address this. Thanks!
